app:
  consumergroup: DetectLanguage
  languagedetected:
    topic: language-detected
  postcreated:
    topic: post-created
  http:
    enabled: false
  amqp:
    enabled: false
  kafka:
    enabled: yes

spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
      group-id: DetectLanguage

    producer:
      bootstrap-servers: localhost:9092
  main:
    web-application-type: none
  jackson:
    serialization:
      fail-on-empty-beans: false